examen_parcial/examen_parcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion_tareas/', include('gestion_tareas.urls'))
]

examen_parcial/gestion_tareas/urls.py
from . import views
from django.urls import path 

app_name = 'gestion_tareas'

urlpatterns = [
    path('',views.index, name='index'),
    path('dashboard',views.dashboard, name='dashboard'),
    path('new',views.new,name='new'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('info/<int:id>', views.info, name='info')
]

examen_parcial/gestion_tareas/models.py
from django.db import models

# Create your models here.
class usuariosDjango(models.Model):
    id = models.IntegerField(primary_key='true', default='')
    nombre = models.CharField(max_length=64, default='')
    apellido = models.CharField(max_length=64, default='')
    tarea = models.CharField(max_length=128, default='')
    fecha = models.DateField(max_length=64, default='')

examen_parcial/gestion_tareas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import usuariosDjango
from django.urls import reverse

# Create your views here.

datos = usuariosDjango.objects.all().order_by('id')

def index(request):
   return render(request, 'gestion_tareas/index.html')

def dashboard(request):
    usuariosInfo = usuariosDjango.objects.all().order_by('id')
    if request.method == 'POST':
        if 'guardar' in request.POST:
            nuevo = []
            id = request.POST.get('idUsuario')
            nombre = request.POST.get('nombreUsuario')
            apellido = request.POST.get('apellidoUsuario')
            tarea = request.POST.get('tareaUsuario')
            fecha = request.POST.get('fechaUsuario')
            nuevo.append(str(id))
            nuevo.append(str(nombre))
            nuevo.append(str(apellido))
            nuevo.append(str(tarea))
            nuevo.append(str(fecha))
            usuariosDjango(id=str(id),nombre=str(nombre),apellido=str(apellido),
            tarea=str(tarea),fecha=str(fecha)).save()
            usuariosInfo = usuariosDjango.objects.all().order_by('id')
    elif 'filtrar' in request.POST:
        personafil = request.POST.get('persona')
        usuariosInfo = usuariosDjango.objects.filter(id=personafil)

    return render(request, 'gestion_tareas/dashboard.html',{
        'usuarios' : usuariosInfo,
    })

def new(request):
   return render(request, 'gestion_tareas/new.html')

def delete(request, id):
    usuario = usuariosDjango.objects.get(id=id)
    usuario.delete()
    return render(request, 'gestion_tareas/dashboard.html'),{
        'usuarios' : usuariosDjango.objects.all(),
    }

def info(request, id):
    usuario = usuariosDjango.objects.get(id=id)
    id = request.POST.get('idUsuario')
    nombre = request.POST.get('nombreUsuario')
    apellido = request.POST.get('apellidoUsuario')
    tarea = request.POST.get('tareaUsuario')
    fecha = request.POST.get('fechaUsuario')
    return render(request, 'gestion_tareas/info.html')

examen_parcial/gestion_tareas/templates/gestion_tareas/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <script src="https://kit.fontawesome.com/8f8726cd66.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm   navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li>
                        <h4>DESARROLLO WEB - PYTHON</h4>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Inicio<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ingresos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Configuración</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Datos Contables</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ventas</a>
                    </li>
            </div>
            <div>
                <button type="" class="bg-success rounded">Salir</button>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <h1 class="pt-4">TAREAS</h1>
            <div class="pt-4 pd-4">
                <form url="{% url 'gestion_tareas:new' %}">
                    {% csrf_token %}
                    <a href="{% url 'gestion_tareas:new' %}" class="bg-success p-2 rounded" style="color:white">+ Nuevo</a>
                </form>
            </div>
            <br>
            <form method="post" url="{% url 'gestion_tareas:dashboard' %}">
                {% csrf_token %}
                <select name="persona">
                    <option value="1">1</option>
                    <option value="2">2</option>
                </select>
                <button type="submit" name="filtrar">Filtrar</button>
            </form>
            <br>
            <button><a href="{% url 'gestion_tareas:dashboard' %}">Reestablecer</a></button>
            
            <div class="table-responsive border-0 pt-4">
                <table class="table align-middle p-4 mb-0 table-hover table-shrink">
                    <!-- Table head -->
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="border-0 rounded-start">ID</th>
                            <th scope="col" class="border-0">Nombre</th>
                            <th scope="col" class="border-0">Apellido</th>
                            <th scope="col" class="border-0">Titulo de tarea</th>
                            <th scope="col" class="border-0">Fecha de publicación</th>
                            <th scope="col" class="border-0 rounded-end">Action</th>
                        </tr>
                    </thead>
                    {% for usuario in usuarios %}
                    <!-- Table body START -->
                    <tbody class="border-top-0">
                        <!-- Table item -->
                        <tr>
                            <!-- Table data -->
                            <td>
                                {{usuario.id}}
                            </td>
                            <td>
                                {{usuario.nombre}}
                            </td>
                            <td>
                                {{usuario.apellido}}
                            </td>
                            <td>
                                <h6 class="course-title mt-2 mt-md-0 mb-0"><a>{{usuario.tarea}}</a></h6>
                            </td>

                            <td>{{usuario.fecha}}</td>

                            <td>
                                <div class="d-flex gap-2">
                                    <a href="info/{{usuario.id}}" class="btn btn-primary btn-round mb-0" data-bs-toggle="tooltip"
                                        data-bs-placement="top" title="Check"><i class="fa-solid fa-eye"></i></a>
                                    <a href="delete/{{usuario.id}}" class="btn btn-danger btn-round mb-0" data-bs-toggle="tooltip"
                                        data-bs-placement="top" title="Delete"><i class="fa-solid fa-trash-can"></i></a>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                    {% endfor %}
                    <!-- Table body END -->
                </table>
            </div>
    </section>
</body>

</html>

examen_parcial/gestion_tareas/templates/gestion_tareas/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Examen Parcial</title>
    <link rel="stylesheet" href="styles.css">
    <script src="https://kit.fontawesome.com/8f8726cd66.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <section class="vh-100">
        <div class="container-fluid h-custom">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <form>
                <!-- Email input -->
                <div class="form-outline mb-4">
                  <input type="email" id="form3Example3" class="form-control form-control-lg"
                    placeholder="Ingresa tu correo" />
                  <label class="form-label" for="form3Example3">Correo electrónico</label>
                </div>
      
                <!-- Password input -->
                <div class="form-outline mb-3">
                  <input type="password" id="form3Example4" class="form-control form-control-lg"
                    placeholder="Ingresa tu contraseña" />
                  <label class="form-label" for="form3Example4">Contraseña</label>
                </div>
      
                <div class="d-flex justify-content-between align-items-center">
                  <!-- Checkbox -->
                  <div class="form-check mb-0">
                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                    <label class="form-check-label" for="form2Example3">
                      Recuérdame
                    </label>
                  </div>
                  <a href="#!" class="text-body">¿Olvido su contraseña?</a>
                </div>
      
                <div class="text-center text-lg-start mt-4 pt-2">
                  <button type="button" class="btn btn-primary btn-lg"
                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Ingresar</button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">¿No tienes una cuenta? <a href="#!"
                      class="link-danger">Regístrate</a></p>
                </div>
      
              </form>
            </div>
          </div>
        </div>
        <div
          class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
          <!-- Copyright -->
          <div class="text-white mb-3 mb-md-0">
            Curso de desarrollo web con Python - Pontificia Universidad Católica del Perú
          </div>
          <!-- Copyright -->
      
          <!-- Right -->
          <div>
            <a href="https://www.facebook.com/pucp/" class="text-white me-4">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="https://twitter.com/pucp" class="text-white me-4">
              <i class="fab fa-twitter"></i>
            </a>
          </div>
          <!-- Right -->
        </div>
      </section>
</body>
</html>

examen_parcial/gestion_tareas/templates/gestion_tareas/info.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de tareas</title>
    <script src="https://kit.fontawesome.com/8f8726cd66.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm   navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li>
                        <h4>DESARROLLO WEB - PYTHON</h4>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Inicio<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ingresos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Configuración</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Datos Contables</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ventas</a>
                    </li>
            </div>
            <div>
                <button type="" class="bg-success rounded">Salir</button>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <h1 class="pt-4">DETALLE DE TAREAS</h1>

            <div class="table-responsive border-0 pt-4">
                <table class="table align-middle p-4 mb-0 table-hover table-shrink">
                    <!-- Table head -->
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="border-0 rounded-start">ID</th>
                            <th scope="col" class="border-0">Nombre</th>
                            <th scope="col" class="border-0">Apellido</th>
                            <th scope="col" class="border-0">Titulo de tarea</th>
                            <th scope="col" class="border-0">Fecha de publicación</th>
                            <th scope="col" class="border-0 rounded-end">Acción</th>
                        </tr>
                    </thead>
                   
                    <!-- Table body START -->
                    <tbody class="border-top-0">
						
							<!-- Table item -->
							<tr>
								<!-- Table data -->
								<td>
									idUsuario
								</td>
								<td>
									nombreUsuario
								</td>
								<td>
									apellidoUsuario
								</td>
								<td>
									tareaUsuario
								</td>
								<td>
									fechaUsuario
								</td>

								<td>
									<div class="d-flex gap-2">
										<a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary btn-round mb-0" data-bs-toggle="tooltip"
											data-bs-placement="top" title="Guardar"><i class="fa-sharp fa-solid fa-arrow-left"></i></a>
									</div>
								</td>
							</tr>
                            
                    </tbody>
                    <!-- Table body END -->
                </table>
            </div>
    </section>
</body>

</html>

examen_parcial/gestion_tareas/templates/gestion_tareas/new.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de tareas</title>
    <script src="https://kit.fontawesome.com/8f8726cd66.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm   navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li>
                        <h4>DESARROLLO WEB - PYTHON</h4>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Inicio<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ingresos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Configuración</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Datos Contables</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ventas</a>
                    </li>
            </div>
            <div>
                <button type="" class="bg-success rounded">Salir</button>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <h1 class="pt-4">REGISTRO DE TAREAS</h1>

            <div class="table-responsive border-0 pt-4">
                <table class="table align-middle p-4 mb-0 table-hover table-shrink">
                    <!-- Table head -->
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="border-0 rounded-start">ID</th>
                            <th scope="col" class="border-0">Nombre</th>
                            <th scope="col" class="border-0">Apellido</th>
                            <th scope="col" class="border-0">Titulo de tarea</th>
                            <th scope="col" class="border-0">Fecha de publicación</th>
                            <th scope="col" class="border-0 rounded-end">Acción</th>
                        </tr>
                    </thead>
                    
                    <!-- Table body START -->
                    <tbody class="border-top-0">
						<form method="post" action="{% url 'gestion_tareas:dashboard' %}">
						{% csrf_token %}
							<!-- Table item -->
							<tr>
								<!-- Table data -->
								<td>
									<input type="number" name="idUsuario" style='width: 40px;'>
								</td>
								<td>
									<input type="text" name="nombreUsuario" style='width: 150px;'>
								</td>
								<td>
									<input type="text" name="apellidoUsuario" style='width: 150px;'>
								</td>
								<td>
									<input type="text" name="tareaUsuario" style='width: 250px;'>
								</td>
								<td>
									<input type="date" name="fechaUsuario" style='width: 150px;'>
								</td>

								<td>
									<div class="d-flex gap-2">
										<button type="submit" name="guardar" href="dashboard" class="btn btn-primary btn-round mb-0" data-bs-toggle="tooltip"
											data-bs-placement="top" title="Guardar"><i class="fas fa-save"></i></button>
									</div>
								</td>
							</tr>
						</form>
                    </tbody>
                    <!-- Table body END -->
                </table>
            </div>
    </section>
</body>

</html>